server = [
    ["bqq_current_player_Count", "bandarqq_pro_b", "1"],
    ["bqq_current_player_Count", "bandarqq_pro_a", "1"],
    ["qiuqiu_current_player_Count", "qiuqiu_pro_a", "1"],
    ["qiuqiu_current_player_Count", "qiuqiu_pro_b", "1"],
    ["sangong_current_player_Count", "sangong_pro_a", "1"],
    ["sangong_current_player_Count", "sangong_pro_b", "1"],
    ["current_player_Count", "texas_pro_a", "1"],
    ["current_player_Count", "texas_pro_b", "1"],
    ["dominoes_current_player_Count", "dominoes_pro_a", "1"],
    ["dominoes_current_player_Count", "dominoes_pro_b", "1"],
    ["dummy_current_player_Count", "dummy_a", "1"],
    ["dummy_current_player_Count", "dummy_b", "1"],
    ["kaeng_current_player_num", "kaeng_pro_a", "1"],
    ["kaeng_current_player_num", "kaeng_pro_b", "1"],
    ["remi_current_player_num", "remi_pro_a", "1"],
    ["remi_current_player_num", "remi_pro_b", "1"],
    ["royalwin_current_player_num", "royalwin_pro_a", "1"],
    ["royalwin_current_player_num", "royalwin_pro_b", "1"],
]
baseURL = "http://172.13.6.13:9991/api/v1/query?"

[bot]
FunItem = [
    "/AllGame",
    "/GameClinetVersion",
]


[GameAll]

Info = [
    ["/Thailand", "/Indonesia"],
    ["/Dummy", "/SanGong", "/Kaeng"],
    ["/Domino", "/RoyalWin", "/BandarQQ", "/QiuQiu", "/Texas", "/Remi"],
    ["2009", "2014", "2022", "2012", "2004", "2013"]
]







